// <auto-generated />
using System;
using DididaiApp.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DididaiApp.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DididaiApp.Core.Models.Colaboracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Colaboraciones");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Colaboracion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DididaiApp.Core.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AceptaPrivacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("DididaiApp.Core.Models.AportacionUnica", b =>
                {
                    b.HasBaseType("DididaiApp.Core.Models.Colaboracion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AportacionUnica");
                });

            modelBuilder.Entity("DididaiApp.Core.Models.CuotaDomiciliada", b =>
                {
                    b.HasBaseType("DididaiApp.Core.Models.Colaboracion");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<int>("Modalidad")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("CuotaDomiciliada");
                });

            modelBuilder.Entity("DididaiApp.Core.Models.Teaming", b =>
                {
                    b.HasBaseType("DididaiApp.Core.Models.Colaboracion");

                    b.HasDiscriminator().HasValue("Teaming");
                });

            modelBuilder.Entity("DididaiApp.Core.Models.Colaboracion", b =>
                {
                    b.HasOne("DididaiApp.Core.Models.Socio", "Socio")
                        .WithMany("Colaboraciones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("DididaiApp.Core.Models.Socio", b =>
                {
                    b.Navigation("Colaboraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
